[context.production]
command = "hugo -D"

[context.production.environment]
  HUGO_VERSION = "0.69.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.69.0"

[context.hugo]
command = "hugo -D"
